# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_channel_slideshare_create:
    pattern: /channel/slideshare/create
    defaults: { _controller: CampaignChainChannelSlideShareBundle:SlideShare:create }

campaignchain_channel_slideshare_new:
    pattern: /channel/slideshare/new
    defaults: { _controller: CampaignChainChannelSlideShareBundle:SlideShare:new }
    