# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#    campaign_chain_channel_slide_share.example:
#        class: CampaignChain\Channel\SlideShareBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    campaignchain.channel.slideshare.rest.client:
        class: CampaignChain\Channel\SlideShareBundle\REST\SlideShareClient
        calls:
            - [setContainer, ["@service_container"]]